/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectswaggy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avaneesh Koushik
 */
public class dpDeliveryHistory extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    String dpid;
    //String oid;
    /**
     * Creates new form dpDeliveryHistory
     */
    public dpDeliveryHistory(Connection con,String dpid) {
        initComponents();
        this.con=con;
        this.dpid=dpid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dpHistory = new javax.swing.JTable();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dpHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Date", "Pincode", "Amount"
            }
        ));
        dpHistory.setFocusable(false);
        jScrollPane2.setViewportView(dpHistory);

        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(refresh)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        String sqlu = "select o.o_id,o.delv_date,oa.o_pincode,p.total_price from orders o,order_address oa,payment p where o.dp_id='"+dpid+"' and o.o_address=oa.o_address and p.o_id=o.o_id and trunc(o.delv_date)=trunc(current_date)";
        //JOptionPane.showMessageDialog(this,sqlu);
        try (Statement stmt = con.createStatement()) {//(Statement stmt = con.createStatement())
//            ps = con.prepareStatement(sqlu);
            ResultSet rs = stmt.executeQuery(sqlu);
//            ResultSetMetaData rsmd =rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel) dpHistory.getModel();
//            int cols=rsmd.getColumnCount();
//            String[] colName=new String[cols];
//            for (int i=0;i<cols;i++)
//            {
//                colName[i]=rsmd.getColumnName(i+1);
//            }
//            model.setColumnIdentifiers(colName);
            String oid,date,pincode,amt;
            int sno=1;
            while(rs.next())
            {
                //JOptionPane.showMessageDialog(this,"good");
                oid=rs.getString("o_id");
                date=rs.getString("delv_date");
                pincode=rs.getString("o_pincode");
                amt=rs.getString("total_price");
                String[] row={oid,date,pincode,amt};
                JOptionPane.showMessageDialog(this,row);
                model.addRow(row);
                sno+=1;
            }
                  
            //rs.next();
//            while (rs.next()) {
//                //JOptionPane.showMessageDialog(this,rs.getString("eid")+"  "+rs.getString("ename")+"  "+rs.getString("designation"));
//                JOptionPane.showMessageDialog(this,"hello");
//                dpCustName.setText(rs.getString("c_name"));
//                dpCustPhone.setText(rs.getString("c_phno"));
//                dpCustAddress.setText(rs.getString("o_address"));
//                //dpCPincode.setText(rs.getString("o_pincode"));
//            }
        } catch (SQLException e) {
            //Logger.getLogger(bank.class.getName()).log(Level.SEVERE,null, e);
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dpDeliveryHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dpDeliveryHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dpDeliveryHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dpDeliveryHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new dpDeliveryHistory().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dpHistory;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
