/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectswaggy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Avaneesh Koushik
 */
public class dptoRestaurant extends javax.swing.JFrame {
        Connection con;
    Statement st;
    PreparedStatement ps;
    String dpid;
    String oid;
    /**
     * Creates new form dptoRestaurant
     */
    public dptoRestaurant(Connection con,String dpid) {
        initComponents();
        this.con=con;
        this.dpid=dpid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        dpRestName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dpRestPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dpRestAddress = new javax.swing.JTextArea();
        refreshCOR = new javax.swing.JButton();
        pickupStatus = new javax.swing.JCheckBox();
        pickedUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Restaurant Name:");

        dpRestName.setFocusable(false);
        dpRestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpRestNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Restaurant Phone :");

        dpRestPhone.setFocusable(false);
        dpRestPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpRestPhoneActionPerformed(evt);
            }
        });

        jLabel7.setText("Restaurant Address :");

        dpRestAddress.setColumns(20);
        dpRestAddress.setRows(5);
        dpRestAddress.setFocusable(false);
        jScrollPane1.setViewportView(dpRestAddress);

        refreshCOR.setText("Refresh");
        refreshCOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCORActionPerformed(evt);
            }
        });

        pickupStatus.setText("Order Picked up");
        pickupStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupStatusActionPerformed(evt);
            }
        });

        pickedUp.setText("Picked Up");
        pickedUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickedUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshCOR)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dpRestName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dpRestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pickupStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(pickedUp))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(refreshCOR)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dpRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dpRestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickupStatus)
                    .addComponent(pickedUp))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpRestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpRestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpRestNameActionPerformed

    private void dpRestPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpRestPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpRestPhoneActionPerformed

    private void refreshCORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCORActionPerformed
        // TODO add your handling code here:
        String sqlu = "select o.o_id,r.r_name,r.r_address,rp.r_phone from restaurant r,orders o,res_phone rp where o.dp_id='"+dpid+"'and o.r_id=r.r_id and r.r_id=rp.r_id";
        JOptionPane.showMessageDialog(this,sqlu);
        try (Statement stmt = con.createStatement()) {
            //ps = con.prepareStatement(sqlu);
            ResultSet rs = stmt.executeQuery(sqlu);
            //rs.next();
            while (rs.next()) {
                //JOptionPane.showMessageDialog(this,rs.getString("eid")+"  "+rs.getString("ename")+"  "+rs.getString("designation"));
                JOptionPane.showMessageDialog(this,"hello");
                dpRestName.setText(rs.getString("r_name"));
                dpRestAddress.setText(rs.getString("r_address"));
                dpRestPhone.setText(rs.getString("r_phone"));
                oid=rs.getString("o_id");
            }
        } catch (SQLException e) {
            //Logger.getLogger(bank.class.getName()).log(Level.SEVERE,null, e);
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_refreshCORActionPerformed

    private void pickupStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickupStatusActionPerformed

    private void pickedUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickedUpActionPerformed
        // TODO add your handling code here:
        if(pickupStatus.isSelected()){    
            JOptionPane.showMessageDialog(this,"Selected");
            try{
                String sql = "update orders set status='OUT FOR DELIVERY'where o_id='"+oid+"'";
                ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(this,"Updated status. Close this tab");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select check box to confirm");
        }
    }//GEN-LAST:event_pickedUpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dptoRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dptoRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dptoRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dptoRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new dptoRestaurant().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dpRestAddress;
    private javax.swing.JTextField dpRestName;
    private javax.swing.JTextField dpRestPhone;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pickedUp;
    private javax.swing.JCheckBox pickupStatus;
    private javax.swing.JButton refreshCOR;
    // End of variables declaration//GEN-END:variables
}
